

-- SELECT * FROM customer limit 20

-- Q1. What is the total revenue generated by make vs female customers?

-- SELECT gender , SUM(purchased_amount) AS revenue
-- FROM customer
-- GROUP BY gender

-- Q2. Which customer used a discount but still spent more than the average purchase amount?

-- SELECT customer_id, purchased_amount
-- FROM customer
-- WHERE discount_applied = 'Yes' AND purchased_amount >= (SELECT AVG (purchased_amount) FROM customer)

-- Q3. Which are the top 5 products with the highest average review rating?

-- SELECT item_purchased , ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
-- FROM customer
-- GROUP BY item_purchased
-- ORDER BY AVG(review_rating) DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- SELECT shipping_type,
-- ROUND(AVG(purchased_amount),2)
-- FROM customer
-- WHERE shipping_type in ('Standard' , 'Express')
-- GROUP BY shipping_type

-- Q5. Segment customers into new , old ,loyal based on their total number of previous purchase

-- WITH customer_type AS (
-- SELECT customer_id , previous_purchases ,
-- CASE 
-- 	WHEN previous_purchases = 1 THEN 'New'
-- 	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
-- 	ELSE 'Loyal'
-- 	END AS customer_segment
-- 	FROM customer
-- )
-- SELECT customer_segment, COUNT(*) as "Number of Customers"
-- FROM customer_type
-- GROUP BY customer_segment

-- Q6. What are the top 3 most purchased products within each category?

-- WITH item_counts AS (
-- SELECT category,
-- item_purchased,
-- COUNT(customer_id) AS total_orders,
-- ROW_NUMBER() OVER(partition by category ORDER BY COUNT(customer_id) DESC) AS item_rank
-- FROM customer
-- GROUP BY category,item_purchased
-- )

-- SELECT item_rank , category , item_purchased , total_orders
-- FROM item_counts
-- WHERE item_rank<=3;

-- Q7. What is the total contribution of each age group

-- SELECT age_group, 
-- SUM(purchased_amount) AS total_revenue
-- FROM customer
-- GROUP BY age_group
-- ORDER BY total_revenue DESC ;